# Generated by Django 4.0.4 on 2022-05-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль сотрудника', 'verbose_name_plural': 'Профили сотрудников'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='user_images/default.png', upload_to='user_images', verbose_name='Фото сотрудника'),
        ),
    ]
