# Generated by Django 4.0.4 on 2022-05-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_options_alter_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='info',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
