# Generated by Django 4.0.4 on 2022-05-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='info',
        ),
        migrations.AddField(
            model_name='profile',
            name='userfirstname',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='profile',
            name='userlastname',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='profile',
            name='userpatronymic',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='profile',
            name='userposition',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='profile',
            name='usertelnumber',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='Телефон'),
        ),
    ]
