# Generated by Django 4.0.4 on 2022-05-27 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exnumber', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Внутренний номер')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Название прибора')),
                ('modificname', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Модификация прибора')),
                ('typename', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Тип прибора')),
                ('lot', models.CharField(default='', max_length=100, verbose_name='Заводской номер')),
                ('yearmanuf', models.IntegerField(blank=True, default='', null=True, verbose_name='Год выпуска')),
                ('status', models.CharField(choices=[('Э', 'В эксплуатации'), ('С', 'Списан'), ('Р', 'Резерв'), ('Д', 'Другое')], default='Эксплуатируется', max_length=300, null=True)),
                ('calinterval', models.IntegerField(blank=True, default='', null=True, verbose_name='МежМетрологический интервал, месяцев')),
                ('docs', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Перечень документов и принадлежностей')),
                ('yearintoservice', models.IntegerField(blank=True, default='0', null=True, verbose_name='Год ввода в эксплуатацию')),
                ('new', models.CharField(default='новый', max_length=100, verbose_name='Новый или б/у')),
                ('invnumber', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Инвентарный номер')),
            ],
            options={
                'verbose_name': 'Прибор',
                'verbose_name_plural': 'Приборы',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=100, verbose_name='Производитель')),
                ('companyAdress', models.CharField(blank=True, default='', max_length=200, verbose_name='Адрес')),
                ('country', models.CharField(blank=True, default='Россия', max_length=200, verbose_name='Страна')),
                ('telnumber', models.CharField(blank=True, default='', max_length=200, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomnumber', models.CharField(default='', max_length=10, verbose_name='Номер комнаты')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
            },
        ),
        migrations.CreateModel(
            name='Roomschange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, db_index=True, verbose_name='Дата перемещения')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='equipment.equipment')),
                ('roomnumber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment.rooms')),
            ],
            options={
                'verbose_name': 'Дата перемещения прибора',
                'verbose_name_plural': 'Даты перемещения приборов',
            },
        ),
        migrations.CreateModel(
            name='Personchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, db_index=True, verbose_name='Дата изменения ответственного')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='equipment.equipment')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Дата изменения ответственного',
                'verbose_name_plural': 'Даты изменения ответственных',
            },
        ),
        migrations.CreateModel(
            name='MeasurEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reestr', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Номер в Госреестре')),
                ('measurydiapason', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Диапазон измерений')),
                ('accuracity', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Класс точности /(разряд/), погрешность и /(или/) неопределённость /(класс, разряд/)')),
                ('equipment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='equipment.equipment')),
            ],
            options={
                'verbose_name': 'Средство измерения',
                'verbose_name_plural': 'Средства измерения',
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment.manufacturer', verbose_name='Производитель'),
        ),
    ]
