# Generated by Django 4.0.4 on 2022-04-29 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ViscosityMJL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('lot', models.CharField(max_length=100, verbose_name='Партия')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Температура, ℃')),
                ('termostatition', models.BooleanField(verbose_name='Термостатировано не менее 20 минут')),
                ('temperatureCheck', models.BooleanField(verbose_name='Температура контролируется внешним поверенным термометром')),
                ('termometer', models.CharField(max_length=10, verbose_name='Внутренний номер термометра')),
                ('ViscosimeterNumber1', models.CharField(max_length=10, verbose_name='Заводской номер вискозиметра № 1')),
                ('Konstant1', models.FloatField(verbose_name='Константа вискозиметра № 1')),
                ('ViscosimeterNumber2', models.CharField(max_length=10, verbose_name='Заводской номер вискозиметра № 1')),
                ('Konstant2', models.FloatField(verbose_name='Константа вискозиметра № 2')),
                ('plustimemin11', models.FloatField(verbose_name='Время истечения 11, + мин')),
                ('plustimesek11', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Время истечения 11, + cек')),
                ('plustimemin21', models.FloatField(verbose_name='Время истечения 21, + мин')),
                ('plustimesek21', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Время истечения 21, + cек')),
                ('plustimemin12', models.FloatField(verbose_name='Время истечения 12, + мин')),
                ('plustimesek12', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Время истечения 12, + cек')),
                ('plustimemin22', models.FloatField(verbose_name='Время истечения 22, + мин')),
                ('plustimesek22', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Время истечения 22, + cек')),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
