# Generated by Django 4.0.4 on 2022-05-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viscosityattestation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viscositymjl',
            name='kriteriy',
            field=models.CharField(default='0,2', max_length=4, verbose_name='Критерий приемлемости измерений'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='plustimemin11',
            field=models.DecimalField(decimal_places=0, max_digits=6, verbose_name='Время истечения 11, + мин'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='plustimemin12',
            field=models.DecimalField(decimal_places=0, max_digits=6, verbose_name='Время истечения 12, + мин'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='plustimemin21',
            field=models.DecimalField(decimal_places=0, max_digits=6, verbose_name='Время истечения 21, + мин'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='plustimemin22',
            field=models.DecimalField(decimal_places=0, max_digits=6, verbose_name='Время истечения 22, + мин'),
        ),
    ]
