# Generated by Django 4.0.4 on 2022-04-29 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viscosityattestation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viscositymjl',
            options={'verbose_name': 'Измерение кинематической вязкости', 'verbose_name_plural': 'Измерения кинематической вязкости'},
        ),
        migrations.AddField(
            model_name='viscositymjl',
            name='ndocument',
            field=models.CharField(choices=[('ГОСТ 33', 'ГОСТ 33'), ('МИ-01', 'МИ-01'), ('оценка', 'оценка вязкости')], default='МИ-01', max_length=100, verbose_name='Метод испытаний'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='performer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
    ]
