# Generated by Django 4.0.4 on 2022-05-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viscosityattestation', '0002_remove_viscositymjl_time12_sec_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viscositymjl',
            name='time12_sec',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=6, verbose_name='Время истечения 11, в секундах'),
        ),
        migrations.AddField(
            model_name='viscositymjl',
            name='time1_avg',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=6, verbose_name='Время истечения среднее 1, в секундах'),
        ),
        migrations.AddField(
            model_name='viscositymjl',
            name='time21_sec',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=6, verbose_name='Время истечения 11, в секундах'),
        ),
        migrations.AddField(
            model_name='viscositymjl',
            name='time22_sec',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=6, verbose_name='Время истечения 11, в секундах'),
        ),
        migrations.AddField(
            model_name='viscositymjl',
            name='time2_avg',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=6, verbose_name='Время истечения среднее 2, в секундах'),
        ),
        migrations.AddField(
            model_name='viscositymjl',
            name='viscosity1',
            field=models.DecimalField(decimal_places=6, default='0', max_digits=20, verbose_name='Вязкость кинематическая 1'),
        ),
        migrations.AddField(
            model_name='viscositymjl',
            name='viscosity2',
            field=models.DecimalField(decimal_places=6, default='0', max_digits=20, verbose_name='Вязкость кинематическая 2'),
        ),
    ]
