# Generated by Django 4.0.4 on 2022-05-15 17:05

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('viscosityattestation', '0002_viscositymjl_kriteriy_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='viscositymjl',
            managers=[
                ('total', django.db.models.manager.Manager()),
            ],
        ),
    ]
