# Generated by Django 4.0.4 on 2022-05-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viscosityattestation', '0003_viscositymjl_time12_sec_viscositymjl_time1_avg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viscositymjl',
            name='accMeasurement',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=3, verbose_name='Оценка приемлемости измерений'),
        ),
        migrations.AddField(
            model_name='viscositymjl',
            name='viscosityAVG',
            field=models.DecimalField(decimal_places=5, default='0', max_digits=20, verbose_name='Вязкость кинематическая среднее'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='viscosity1',
            field=models.DecimalField(decimal_places=5, default='0', max_digits=20, verbose_name='Вязкость кинематическая 1'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='viscosity2',
            field=models.DecimalField(decimal_places=5, default='0', max_digits=20, verbose_name='Вязкость кинематическая 2'),
        ),
    ]
