# Generated by Django 4.0.4 on 2022-05-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viscosityattestation', '0004_viscositymjl_accmeasurement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viscositymjl',
            name='cause',
            field=models.CharField(default=1, max_length=100, verbose_name='Причина'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viscositymjl',
            name='delta',
            field=models.CharField(default=1, max_length=100, verbose_name='Не превышает Δ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viscositymjl',
            name='resultMeas',
            field=models.CharField(default='неудовлетворительно', max_length=100, verbose_name='Результат измерений уд/неуд'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='kriteriy',
            field=models.DecimalField(decimal_places=1, default=0.2, max_digits=2, verbose_name='Критерий приемлемости измерений'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='time12_sec',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=6, verbose_name='Время истечения 12, в секундах'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='time21_sec',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=6, verbose_name='Время истечения 21, в секундах'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='time22_sec',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=6, verbose_name='Время истечения 22, в секундах'),
        ),
    ]
