# Generated by Django 4.0.4 on 2022-05-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viscosityattestation', '0004_alter_viscositymjl_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viscositymjl',
            name='plustimemin12_sec',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=6, verbose_name='Время истечения 11, в секундах'),
        ),
    ]
