# Generated by Django 4.0.4 on 2022-05-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viscosityattestation', '0005_viscositymjl_plustimemin12_sec'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viscositymjl',
            old_name='plustimemin11_sec',
            new_name='time11_sec',
        ),
        migrations.RenameField(
            model_name='viscositymjl',
            old_name='plustimemin12_sec',
            new_name='time12_sec',
        ),
        migrations.AddField(
            model_name='viscositymjl',
            name='time1_avg',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=6, verbose_name='Время истечения среднее 1, в секундах'),
        ),
        migrations.AddField(
            model_name='viscositymjl',
            name='time21_sec',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=6, verbose_name='Время истечения 11, в секундах'),
        ),
        migrations.AddField(
            model_name='viscositymjl',
            name='time22_sec',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=6, verbose_name='Время истечения 11, в секундах'),
        ),
        migrations.AddField(
            model_name='viscositymjl',
            name='time2_avg',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=6, verbose_name='Время истечения среднее 2, в секундах'),
        ),
    ]
