# Generated by Django 4.0.4 on 2022-05-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viscosityattestation', '0006_rename_plustimemin11_sec_viscositymjl_time11_sec_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viscositymjl',
            name='viscosity1',
            field=models.DecimalField(decimal_places=6, default='0', max_digits=20, verbose_name='Вязкость кинематическая 1'),
        ),
        migrations.AddField(
            model_name='viscositymjl',
            name='viscosity2',
            field=models.DecimalField(decimal_places=6, default='0', max_digits=20, verbose_name='Вязкость кинематическая 2'),
        ),
    ]
