# Generated by Django 4.0.4 on 2022-05-16 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viscosityattestation', '0007_viscositymjl_viscosity1_viscositymjl_viscosity2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viscositymjl',
            name='time11_sec',
        ),
        migrations.RemoveField(
            model_name='viscositymjl',
            name='time12_sec',
        ),
        migrations.RemoveField(
            model_name='viscositymjl',
            name='time1_avg',
        ),
        migrations.RemoveField(
            model_name='viscositymjl',
            name='time21_sec',
        ),
        migrations.RemoveField(
            model_name='viscositymjl',
            name='time22_sec',
        ),
        migrations.RemoveField(
            model_name='viscositymjl',
            name='time2_avg',
        ),
        migrations.RemoveField(
            model_name='viscositymjl',
            name='viscosity1',
        ),
        migrations.RemoveField(
            model_name='viscositymjl',
            name='viscosity2',
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='Konstant1',
            field=models.DecimalField(decimal_places=10, default='0', max_digits=20, verbose_name='Константа вискозиметра № 1'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='Konstant2',
            field=models.DecimalField(decimal_places=10, default='0', max_digits=20, verbose_name='Константа вискозиметра № 2'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='ViscosimeterNumber1',
            field=models.CharField(default='0', max_length=10, verbose_name='Заводской номер вискозиметра № 1'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='ViscosimeterNumber2',
            field=models.CharField(default='0', max_length=10, verbose_name='Заводской номер вискозиметра № 2'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='name',
            field=models.CharField(default='0', max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='performer',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='plustimemin11',
            field=models.DecimalField(decimal_places=0, default='0', max_digits=6, verbose_name='Время истечения 11, + мин'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='plustimemin12',
            field=models.DecimalField(decimal_places=0, default='0', max_digits=6, verbose_name='Время истечения 12, + мин'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='plustimemin21',
            field=models.DecimalField(decimal_places=0, default='0', max_digits=6, verbose_name='Время истечения 21, + мин'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='plustimemin22',
            field=models.DecimalField(decimal_places=0, default='0', max_digits=6, verbose_name='Время истечения 22, + мин'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='plustimesek11',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=5, verbose_name='Время истечения 11, + cек'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='plustimesek12',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=5, verbose_name='Время истечения 12, + cек'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='plustimesek21',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=5, verbose_name='Время истечения 21, + cек'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='plustimesek22',
            field=models.DecimalField(decimal_places=2, default='2', max_digits=5, verbose_name='Время истечения 22, + cек'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='temperature',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=5, verbose_name='Температура, ℃'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='temperatureCheck',
            field=models.BooleanField(blank=True, verbose_name='Температура контролируется внешним поверенным термометром'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='termometer',
            field=models.CharField(default='0', max_length=10, verbose_name='Внутренний номер термометра'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='termostatition',
            field=models.BooleanField(blank=True, verbose_name='Термостатировано не менее 20 минут'),
        ),
    ]
