# Generated by Django 4.0.4 on 2022-05-16 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viscosityattestation', '0010_alter_viscositymjl_performer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viscositymjl',
            name='performer',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
