# Generated by Django 4.0.4 on 2022-05-16 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viscosityattestation', '0011_alter_viscositymjl_performer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viscositymjl',
            name='performer',
        ),
    ]
