# Generated by Django 4.0.4 on 2022-05-17 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_delete_attestationj'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttestationJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата cсоздания журнала')),
                ('name', models.CharField(default='0', max_length=100, verbose_name='Наименование журнала')),
                ('ndocument', models.CharField(default='', max_length=100, verbose_name='Методы испытаний')),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ответственный за ведение журнала')),
            ],
            options={
                'verbose_name': 'Журнал аттестации',
                'verbose_name_plural': 'Журналы аттестации',
            },
        ),
    ]
