# Generated by Django 4.0.4 on 2022-05-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attestationj',
            name='for_url',
            field=models.CharField(default='', max_length=100, verbose_name='Методы испытаний'),
        ),
        migrations.AlterField(
            model_name='attestationj',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Наименование журнала'),
        ),
    ]
