# Generated by Django 4.0.4 on 2022-05-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_attestationj_for_url_alter_attestationj_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attestationj',
            name='for_url',
            field=models.CharField(default='', max_length=100, verbose_name='Адрес журнала'),
        ),
    ]
