# Generated by Django 4.0.4 on 2022-05-27 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viscosimeters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kalibration',
            name='id_Viscosimeter',
        ),
        migrations.DeleteModel(
            name='Viscosimeters',
        ),
    ]
