# Generated by Django 4.0.4 on 2022-05-18 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viscosimeters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viscosimeters',
            name='dateCal',
            field=models.DateField(default=datetime.datetime(2022, 5, 18, 15, 3, 45, 115826), verbose_name='Дата калибровки'),
        ),
        migrations.AddField(
            model_name='viscosimeters',
            name='konstant',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=7, verbose_name='Константа'),
        ),
        migrations.AlterField(
            model_name='viscosimeters',
            name='datePov',
            field=models.DateField(default=datetime.datetime(2022, 5, 18, 15, 3, 45, 115826), verbose_name='Дата поверки'),
        ),
        migrations.AlterField(
            model_name='viscosimeters',
            name='datePovDedlain',
            field=models.DateField(default=datetime.datetime(2022, 5, 18, 15, 3, 45, 115826), verbose_name='Дата окончания поверки'),
        ),
    ]
