# Generated by Django 4.0.4 on 2022-04-28 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viscosimeters', '0002_viscosimeters_companyname_viscosimeters_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='viscosimeters',
            name='viscosity1000',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='viscosity1000_1', to='viscosimeters.viscosimetertype', verbose_name='Средняя вязкость за 1000 сек'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='viscosimeters',
            name='diameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diameter_1', to='viscosimeters.viscosimetertype', verbose_name='Диаметр'),
        ),
        migrations.AlterField(
            model_name='viscosimetertype',
            name='range',
            field=models.CharField(max_length=30, verbose_name='Область измерений, сСт'),
        ),
    ]
