# Generated by Django 4.0.4 on 2022-05-18 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viscosimeters', '0002_viscosimeters_datecal_viscosimeters_konstant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viscosimeters',
            name='dateCal',
            field=models.DateField(default=datetime.datetime(2022, 5, 18, 16, 40, 16, 644760), verbose_name='Дата калибровки'),
        ),
        migrations.AlterField(
            model_name='viscosimeters',
            name='datePov',
            field=models.DateField(default=datetime.datetime(2022, 5, 18, 16, 40, 16, 644760), verbose_name='Дата поверки'),
        ),
        migrations.AlterField(
            model_name='viscosimeters',
            name='datePovDedlain',
            field=models.DateField(default=datetime.datetime(2022, 5, 18, 16, 40, 16, 644760), verbose_name='Дата окончания поверки'),
        ),
        migrations.AlterField(
            model_name='viscosimeters',
            name='konstant',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10, verbose_name='Константа'),
        ),
    ]
