# Generated by Django 4.0.4 on 2022-05-27 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
        ('viscosimeters', '0002_remove_kalibration_id_viscosimeter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viscosimeters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment.equipment', verbose_name='СИ')),
                ('viscosimeterType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='viscosimeters.viscosimetertype', verbose_name='Диаметр')),
            ],
            options={
                'verbose_name': 'Вискозиметр',
                'verbose_name_plural': 'Вискозиметры',
            },
        ),
        migrations.AddField(
            model_name='kalibration',
            name='id_Viscosimeter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='viscosimeters.viscosimeters', verbose_name='Номер вискозиметра'),
            preserve_default=False,
        ),
    ]
