# Generated by Django 4.0.4 on 2022-05-27 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
        ('viscosimeters', '0003_viscosimeters_kalibration_id_viscosimeter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kalibration',
            name='id_Viscosimeter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_Viscosimeter', to='viscosimeters.viscosimeters', verbose_name='Номер вискозиметра'),
        ),
        migrations.AlterField(
            model_name='viscosimeters',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='equipment.equipment', verbose_name='СИ'),
        ),
    ]
