# Generated by Django 4.0.4 on 2022-05-27 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
        ('viscosimeters', '0004_alter_kalibration_id_viscosimeter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kalibration',
            name='id_Viscosimeter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viscosimeters.viscosimeters', verbose_name='Номер вискозиметра'),
        ),
        migrations.AlterField(
            model_name='viscosimeters',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment.equipment', verbose_name='СИ'),
        ),
    ]
