# Generated by Django 4.0.4 on 2022-04-28 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viscosimeters', '0005_remove_viscosimeters_id_viscosimetertype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viscosimeters',
            name='viscosity1000',
        ),
        migrations.AddField(
            model_name='viscosimeters',
            name='id_ViscosimeterType',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='viscosimeters.viscosimetertype', verbose_name='Тип вискозиметра'),
            preserve_default=False,
        ),
    ]
