# Generated by Django 4.0.4 on 2022-05-27 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viscosimeters', '0005_alter_kalibration_id_viscosimeter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viscosimeters',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='viscosimeters',
            name='viscosimeterType',
        ),
        migrations.DeleteModel(
            name='Kalibration',
        ),
        migrations.DeleteModel(
            name='Viscosimeters',
        ),
        migrations.DeleteModel(
            name='ViscosimeterType',
        ),
    ]
