# Generated by Django 4.0.4 on 2022-05-27 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viscosimeters', '0006_remove_viscosimeters_equipment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViscosimeterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pairNumber', models.CharField(max_length=100, verbose_name='Номер пары')),
                ('diameter', models.CharField(max_length=5, verbose_name='Диаметр')),
                ('viscosity1000', models.CharField(max_length=30, verbose_name='Вязкость за 1000 сек, сСт')),
                ('range', models.CharField(max_length=30, verbose_name='Область измерений, сСт')),
                ('type', models.CharField(default='ВПЖ-1', max_length=30, verbose_name='Тип')),
                ('intervalVerification', models.CharField(default='4 года', max_length=30, verbose_name='Межповерочный интервал')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Тип вискозиметра',
                'verbose_name_plural': 'Типы вискозиметров',
            },
        ),
        migrations.CreateModel(
            name='Viscosimeters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='equipment.equipment', verbose_name='СИ')),
                ('viscosimeterType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='viscosimeters.viscosimetertype', verbose_name='Диаметр')),
            ],
            options={
                'verbose_name': 'Вискозиметр',
                'verbose_name_plural': 'Вискозиметры',
            },
        ),
        migrations.CreateModel(
            name='Kalibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateKalib', models.DateField(auto_now_add=True, verbose_name='Дата калибровки')),
                ('konstant', models.DecimalField(decimal_places=6, default='0', max_digits=10, verbose_name='Установленная константа')),
                ('id_Viscosimeter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viscosimeters.viscosimeters', verbose_name='Номер вискозиметра')),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Калибровка',
                'verbose_name_plural': 'Калибровки',
            },
        ),
    ]
