# Generated by Django 4.0.4 on 2022-05-11 11:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('viscosimeters', '0007_remove_viscosimeters_id_viscosimetertype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viscosimetertype',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viscosimetertype',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
