# Generated by Django 4.0.4 on 2022-05-23 11:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('viscosimeters', '0074_alter_viscosimeters_datecal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viscosimeters',
            name='range',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='range_range', to='viscosimeters.viscosimetertype', verbose_name='Область измерений, сСт'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='viscosimeters',
            name='dateCal',
            field=models.DateField(default=datetime.datetime(2022, 5, 23, 11, 1, 23, 852883, tzinfo=utc), verbose_name='Дата калибровки'),
        ),
        migrations.AlterField(
            model_name='viscosimeters',
            name='datePov',
            field=models.DateField(default=datetime.datetime(2022, 5, 23, 11, 1, 23, 852883, tzinfo=utc), verbose_name='Дата поверки'),
        ),
        migrations.AlterField(
            model_name='viscosimeters',
            name='datePovDedlain',
            field=models.DateField(default=datetime.datetime(2022, 5, 23, 14, 1, 23, 852883), verbose_name='Дата окончания поверки'),
        ),
        migrations.AlterField(
            model_name='viscosimeters',
            name='diameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diameter_diameter', to='viscosimeters.viscosimetertype', verbose_name='Диаметр'),
        ),
    ]
