# Generated by Django 4.0.4 on 2022-05-23 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viscosimeters', '0075_viscosimeters_range_alter_viscosimeters_datecal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viscosimeters',
            name='viscosity1000',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='viscosity1000_on', to='viscosimeters.viscosimetertype', verbose_name='Диаметр'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='viscosimeters',
            name='dateCal',
            field=models.DateField(auto_now_add=True, verbose_name='Дата калибровки'),
        ),
        migrations.AlterField(
            model_name='viscosimeters',
            name='datePov',
            field=models.DateField(auto_now_add=True, verbose_name='Дата поверки'),
        ),
        migrations.AlterField(
            model_name='viscosimeters',
            name='datePovDedlain',
            field=models.DateField(auto_now_add=True, verbose_name='Дата окончания поверки'),
        ),
    ]
