# Generated by Django 4.0.4 on 2022-05-24 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viscosimeters', '0077_alter_viscosimeters_viscosity1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viscosimeters',
            old_name='companyName',
            new_name='Manufacturer',
        ),
        migrations.RemoveField(
            model_name='viscosimeters',
            name='dateCal',
        ),
        migrations.RemoveField(
            model_name='viscosimeters',
            name='diameter',
        ),
        migrations.RemoveField(
            model_name='viscosimeters',
            name='konstant',
        ),
        migrations.RemoveField(
            model_name='viscosimeters',
            name='range',
        ),
        migrations.RemoveField(
            model_name='viscosimeters',
            name='viscosity1000',
        ),
        migrations.AddField(
            model_name='viscosimeters',
            name='viscosimeterType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='viscosimeters.viscosimetertype', verbose_name='Диаметр'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kalibration',
            name='dateKalib',
            field=models.DateField(auto_now_add=True, verbose_name='Дата калибровки'),
        ),
        migrations.AlterField(
            model_name='kalibration',
            name='dateKalibNext',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='kalibration',
            name='konstant',
            field=models.DecimalField(decimal_places=6, default='0', max_digits=7, verbose_name='Установленная константа'),
        ),
        migrations.AlterField(
            model_name='viscosimeters',
            name='datePov',
            field=models.DateField(auto_now_add=True, verbose_name='Дата  поверки'),
        ),
        migrations.AlterField(
            model_name='viscosimeters',
            name='datePovDedlain',
            field=models.DateField(verbose_name='Дата окончания поверки'),
        ),
    ]
