# Generated by Django 4.0.4 on 2022-05-25 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viscosimeters', '0078_rename_companyname_viscosimeters_manufacturer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kalibration',
            name='dateKalibNext',
        ),
        migrations.AddField(
            model_name='kalibration',
            name='performer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='companyAdress',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='kalibration',
            name='konstant',
            field=models.DecimalField(decimal_places=6, default='0', max_digits=10, verbose_name='Установленная константа'),
        ),
    ]
