# Generated by Django 4.0.4 on 2022-05-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinematicviscosity', '0002_alter_viscositymjl_konstant1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viscositymjl',
            name='Konstant1',
            field=models.DecimalField(decimal_places=10, default='0', max_digits=20, verbose_name='Константа вискозиметра № 1'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='Konstant2',
            field=models.DecimalField(decimal_places=10, default='0', max_digits=20, verbose_name='Константа вискозиметра № 2'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='accMeasurement',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=3, verbose_name='Оценка приемлемости измерений'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='kriteriy',
            field=models.DecimalField(decimal_places=1, default=0.2, max_digits=2, verbose_name='Критерий приемлемости измерений'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='plustimemin11',
            field=models.DecimalField(decimal_places=0, default='0', max_digits=6, verbose_name='Время истечения 11, + мин'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='plustimemin12',
            field=models.DecimalField(decimal_places=0, default='0', max_digits=6, verbose_name='Время истечения 12, + мин'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='plustimemin21',
            field=models.DecimalField(decimal_places=0, default='0', max_digits=6, verbose_name='Время истечения 21, + мин'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='plustimemin22',
            field=models.DecimalField(decimal_places=0, default='0', max_digits=6, verbose_name='Время истечения 22, + мин'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='plustimesek11',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=5, verbose_name='Время истечения 11, + cек'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='plustimesek12',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=5, verbose_name='Время истечения 12, + cек'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='plustimesek21',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=5, verbose_name='Время истечения 21, + cек'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='plustimesek22',
            field=models.DecimalField(decimal_places=2, default='2', max_digits=5, verbose_name='Время истечения 22, + cек'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='temperature',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=5, verbose_name='Температура, ℃'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='time11_sec',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=6, verbose_name='Время истечения 11, в секундах'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='time12_sec',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=6, verbose_name='Время истечения 12, в секундах'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='time1_avg',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=6, verbose_name='Время истечения среднее 1, в секундах'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='time21_sec',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=6, verbose_name='Время истечения 21, в секундах'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='time22_sec',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=6, verbose_name='Время истечения 22, в секундах'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='time2_avg',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=6, verbose_name='Время истечения среднее 2, в секундах'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='viscosity1',
            field=models.DecimalField(decimal_places=5, default='0', max_digits=20, verbose_name='Вязкость кинематическая 1'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='viscosity2',
            field=models.DecimalField(decimal_places=5, default='0', max_digits=20, verbose_name='Вязкость кинематическая 2'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='viscosityAVG',
            field=models.DecimalField(decimal_places=5, default='0', max_digits=20, verbose_name='Вязкость кинематическая среднее'),
        ),
    ]
