# Generated by Django 4.0.4 on 2022-05-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinematicviscosity', '0003_alter_viscositymjl_konstant1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viscositymjl',
            name='accMeasurement',
            field=models.DecimalField(decimal_places=3, default='0', max_digits=3, verbose_name='Оценка приемлемости измерений'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='time11_sec',
            field=models.DecimalField(decimal_places=3, default='0', max_digits=6, verbose_name='Время истечения 11, в секундах'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='time12_sec',
            field=models.DecimalField(decimal_places=3, default='0', max_digits=6, verbose_name='Время истечения 12, в секундах'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='time1_avg',
            field=models.DecimalField(decimal_places=3, default='0', max_digits=6, verbose_name='Время истечения среднее 1, в секундах'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='time21_sec',
            field=models.DecimalField(decimal_places=3, default='0', max_digits=6, verbose_name='Время истечения 21, в секундах'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='time22_sec',
            field=models.DecimalField(decimal_places=3, default='0', max_digits=6, verbose_name='Время истечения 22, в секундах'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='time2_avg',
            field=models.DecimalField(decimal_places=3, default='0', max_digits=6, verbose_name='Время истечения среднее 2, в секундах'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='viscosity1',
            field=models.DecimalField(decimal_places=6, default='0', max_digits=20, verbose_name='Вязкость кинематическая 1'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='viscosity2',
            field=models.DecimalField(decimal_places=6, default='0', max_digits=20, verbose_name='Вязкость кинематическая 2'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='viscosityAVG',
            field=models.DecimalField(decimal_places=6, default='0', max_digits=20, verbose_name='Вязкость кинематическая среднее'),
        ),
    ]
