# Generated by Django 4.0.4 on 2022-05-20 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kinematicviscosity', '0005_alter_viscositymjl_accmeasurement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viscositymjl',
            name='accMeasurement',
        ),
        migrations.RemoveField(
            model_name='viscositymjl',
            name='viscosityAVG',
        ),
    ]
