# Generated by Django 4.0.4 on 2022-05-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinematicviscosity', '0008_alter_viscositymjl_time1_avg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viscositymjl',
            name='time1_avg',
            field=models.DecimalField(decimal_places=4, default='0', max_digits=6, verbose_name='Время истечения среднее 1, в секундах'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='time2_avg',
            field=models.DecimalField(decimal_places=4, default='0', max_digits=6, verbose_name='Время истечения среднее 2, в секундах'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='viscosity1',
            field=models.DecimalField(decimal_places=7, default='0', max_digits=20, verbose_name='Вязкость кинематическая 1'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='viscosity2',
            field=models.DecimalField(decimal_places=7, default='0', max_digits=20, verbose_name='Вязкость кинематическая 2'),
        ),
    ]
