# Generated by Django 4.0.4 on 2022-05-20 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kinematicviscosity', '0009_alter_viscositymjl_time1_avg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viscositymjl',
            name='viscosity1',
        ),
        migrations.RemoveField(
            model_name='viscositymjl',
            name='viscosity2',
        ),
    ]
