# Generated by Django 4.0.4 on 2022-05-20 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kinematicviscosity', '0010_remove_viscositymjl_viscosity1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viscositymjl',
            name='time1_avg',
        ),
        migrations.RemoveField(
            model_name='viscositymjl',
            name='time2_avg',
        ),
    ]
