# Generated by Django 4.0.4 on 2022-05-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinematicviscosity', '0011_remove_viscositymjl_time1_avg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viscositymjl',
            name='timeK1T1_sec',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=5, verbose_name='Время истечения K1T1, в секундах'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='timeK1T2_sec',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=5, verbose_name='Время истечения K1T2, в секундах'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='timeK2T1_sec',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=5, verbose_name='Время истечения K2T1, в секундах'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='timeK2T2_sec',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=5, verbose_name='Время истечения K2T2, в секундах'),
        ),
    ]
