# Generated by Django 4.0.4 on 2022-05-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinematicviscosity', '0012_alter_viscositymjl_timek1t1_sec_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viscositymjl',
            name='time1_avg',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=5, verbose_name='Время истечения среднее 1, в секундах'),
        ),
        migrations.AddField(
            model_name='viscositymjl',
            name='time2_avg',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=5, verbose_name='Время истечения среднее 2, в секундах'),
        ),
    ]
