# Generated by Django 4.0.4 on 2022-05-20 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kinematicviscosity', '0013_viscositymjl_time1_avg_viscositymjl_time2_avg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viscositymjl',
            old_name='time1_avg',
            new_name='timeK1_avg',
        ),
        migrations.RenameField(
            model_name='viscositymjl',
            old_name='time2_avg',
            new_name='timeK2_avg',
        ),
    ]
