# Generated by Django 4.0.4 on 2022-05-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinematicviscosity', '0015_alter_viscositymjl_timek1t1_sec_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viscositymjl',
            name='timeK1_avg',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=7, verbose_name='Время истечения среднее 1, в секундах'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='timeK2_avg',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=7, verbose_name='Время истечения среднее 2, в секундах'),
        ),
    ]
