# Generated by Django 4.0.4 on 2022-05-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinematicviscosity', '0016_alter_viscositymjl_timek1_avg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viscositymjl',
            name='viscosity1',
            field=models.DecimalField(decimal_places=7, default='0', max_digits=20, verbose_name='Вязкость кинематическая 1'),
        ),
        migrations.AddField(
            model_name='viscositymjl',
            name='viscosity2',
            field=models.DecimalField(decimal_places=7, default='0', max_digits=20, verbose_name='Вязкость кинематическая 2'),
        ),
    ]
