# Generated by Django 4.0.4 on 2022-05-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinematicviscosity', '0017_viscositymjl_viscosity1_viscositymjl_viscosity2'),
    ]

    operations = [
        migrations.AddField(
            model_name='viscositymjl',
            name='accMeasurement',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=5, verbose_name='Оценка приемлемости измерений'),
        ),
        migrations.AddField(
            model_name='viscositymjl',
            name='viscosityAVG',
            field=models.DecimalField(decimal_places=7, default='0', max_digits=20, verbose_name='Вязкость кинематическая среднее'),
        ),
    ]
