# Generated by Django 4.0.4 on 2022-05-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinematicviscosity', '0018_viscositymjl_accmeasurement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viscositymjl',
            name='termostatition_words',
            field=models.CharField(default='0', max_length=1, verbose_name='Термостатировано не менее 20 минут - словами'),
        ),
    ]
