# Generated by Django 4.0.4 on 2022-05-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinematicviscosity', '0020_alter_viscositymjl_accmeasurement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viscositymjl',
            name='constit',
            field=models.CharField(choices=[('on', 'Проба содержит октол/нефть'), ('NOon', 'В пробе нет октола/нефти')], default='Проба содержит октол/нефть', max_length=300),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='accMeasurement',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='Оценка приемлемости измерений'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='cause',
            field=models.CharField(default='', max_length=100, verbose_name='Причина'),
        ),
    ]
