# Generated by Django 4.0.4 on 2022-05-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinematicviscosity', '0021_viscositymjl_constit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viscositymjl',
            name='constit',
            field=models.CharField(choices=[('да', 'Проба содержит октол/нефть'), ('нет', 'В пробе нет октола/нефти'), ('другое', 'другое')], default='Проба содержит октол/нефть', max_length=300),
        ),
    ]
