# Generated by Django 4.0.4 on 2022-05-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinematicviscosity', '0022_alter_viscositymjl_constit'),
    ]

    operations = [
        migrations.AddField(
            model_name='viscositymjl',
            name='abserror',
            field=models.FloatField(null=True, verbose_name='Абсолютная  погрешность'),
        ),
        migrations.AddField(
            model_name='viscositymjl',
            name='abserror_text',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='viscositymjl',
            name='relerror',
            field=models.DecimalField(decimal_places=1, default=0.3, max_digits=3, null=True, verbose_name='Относительная  погрешность'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='accMeasurement',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name='Оценка приемлемости измерений'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='cause',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Причина'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='constit',
            field=models.CharField(choices=[('да', 'Проба содержит октол/нефть'), ('нет', 'В пробе нет октола/нефти'), ('другое', 'другое')], default='Проба содержит октол/нефть', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='date',
            field=models.DateField(auto_now_add=True, db_index=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='delta',
            field=models.CharField(max_length=100, null=True, verbose_name='Не превышает Δ'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='kriteriy',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True, verbose_name='Критерий приемлемости измерений'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='plustimeminK1T1',
            field=models.DecimalField(decimal_places=0, max_digits=3, null=True, verbose_name='Время истечения K1T1, + мин'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='plustimeminK1T2',
            field=models.DecimalField(decimal_places=0, max_digits=3, null=True, verbose_name='Время истечения K1T2, + мин'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='plustimeminK2T1',
            field=models.DecimalField(decimal_places=0, max_digits=3, null=True, verbose_name='Время истечения K2T1, + мин'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='plustimeminK2T2',
            field=models.DecimalField(decimal_places=0, max_digits=3, null=True, verbose_name='Время истечения K2T2, + мин'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='plustimesekK1T1',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Время истечения K1T1, + cек'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='plustimesekK1T2',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Время истечения K1T2, + cек'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='plustimesekK2T1',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Время истечения K2T1, + cек'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='plustimesekK2T2',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Время истечения K2T2, + cек'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='resultMeas',
            field=models.CharField(default='неудовлетворительно', max_length=100, null=True, verbose_name='Результат измерений уд/неуд'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='termostatition_words',
            field=models.CharField(max_length=1, null=True, verbose_name='Термостатировано не менее 20 минут - словами'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='timeK1T1_sec',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name='Время истечения K1T1, в секундах'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='timeK1T2_sec',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name='Время истечения K1T2, в секундах'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='timeK1_avg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name='Время истечения среднее 1, в секундах'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='timeK2T1_sec',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name='Время истечения K2T1, в секундах'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='timeK2T2_sec',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name='Время истечения K2T2, в секундах'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='timeK2_avg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name='Время истечения среднее 2, в секундах'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='viscosity1',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=20, null=True, verbose_name='Вязкость кинематическая 1'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='viscosity2',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=20, null=True, verbose_name='Вязкость кинематическая 2'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='viscosityAVG',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=20, null=True, verbose_name='Вязкость кинематическая среднее'),
        ),
    ]
