# Generated by Django 4.0.4 on 2022-05-23 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viscosimeters', '0070_alter_viscosimeters_datecal_and_more'),
        ('kinematicviscosity', '0023_viscositymjl_abserror_viscositymjl_abserror_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viscositymjl',
            name='ViscosimeterNumber1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='viscosimeters.viscosimeters', verbose_name='Заводской номер вискозиметра № 1'),
        ),
    ]
