# Generated by Django 4.0.4 on 2022-05-23 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viscosimeters', '0073_alter_viscosimeters_datecal_and_more'),
        ('kinematicviscosity', '0025_alter_viscositymjl_viscosimeternumber1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viscositymjl',
            name='ViscosimeterNumber1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ViscosimeterNumber1', to='viscosimeters.viscosimeters', verbose_name='Заводской номер вискозиметра № 1'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='ViscosimeterNumber2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ViscosimeterNumber2', to='viscosimeters.viscosimeters', verbose_name='Заводской номер вискозиметра № 1'),
        ),
    ]
