# Generated by Django 4.0.4 on 2022-05-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinematicviscosity', '0026_alter_viscositymjl_viscosimeternumber1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viscositymjl',
            name='ViscosimeterNumber1',
            field=models.CharField(default='0', max_length=10, verbose_name='Заводской номер вискозиметра № 1'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='ViscosimeterNumber2',
            field=models.CharField(default='0', max_length=10, verbose_name='Заводской номер вискозиметра № 2'),
        ),
    ]
