# Generated by Django 4.0.4 on 2022-05-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinematicviscosity', '0029_viscositymjl_certifiedvalue_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viscositymjl',
            name='deltaOldCertifiedValue',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Оценка разницы с предыдущим значением'),
        ),
    ]
