# Generated by Django 4.0.4 on 2022-05-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinematicviscosity', '0030_viscositymjl_deltaoldcertifiedvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viscositymjl',
            name='oldCertifiedValue',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True, verbose_name='Аттестованное значение'),
        ),
    ]
