# Generated by Django 4.0.4 on 2022-05-24 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kinematicviscosity', '0032_alter_viscositymjl_oldcertifiedvalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viscositymjl',
            name='deltaOldCertifiedValue',
        ),
    ]
