# Generated by Django 4.0.4 on 2022-05-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinematicviscosity', '0033_remove_viscositymjl_deltaoldcertifiedvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='viscositymjl',
            name='name2',
            field=models.CharField(default='0', max_length=100, verbose_name='Наименование'),
        ),
    ]
