# Generated by Django 4.0.4 on 2022-05-24 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kinematicviscosity', '0034_viscositymjl_name2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viscositymjl',
            name='name2',
        ),
    ]
