# Generated by Django 4.0.4 on 2022-05-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinematicviscosity', '0035_remove_viscositymjl_name2'),
    ]

    operations = [
        migrations.AddField(
            model_name='viscositymjl',
            name='deltaOldCertifiedValue',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Оценка разницы с предыдущим значением'),
        ),
        migrations.AddField(
            model_name='viscositymjl',
            name='deltaOldCertifiedValue_text',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='viscositymjl',
            name='resultWarning',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='oldCertifiedValue',
            field=models.CharField(default='', max_length=300, null=True, verbose_name='Предыдущее аттестованное значение'),
        ),
    ]
