# Generated by Django 4.0.4 on 2022-05-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinematicviscosity', '0036_viscositymjl_deltaoldcertifiedvalue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viscositymjl',
            name='deltaOldCertifiedValue',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True, verbose_name='Оценка разницы с предыдущим значением'),
        ),
    ]
