# Generated by Django 4.0.4 on 2022-05-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinematicviscosity', '0037_alter_viscositymjl_deltaoldcertifiedvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='viscositymjl',
            name='lot1',
            field=models.CharField(default='1', max_length=100, verbose_name='Партия'),
            preserve_default=False,
        ),
    ]
