# Generated by Django 4.0.4 on 2022-05-24 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kinematicviscosity', '0038_viscositymjl_lot1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viscositymjl',
            name='lot1',
        ),
    ]
