# Generated by Django 4.0.4 on 2022-05-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinematicviscosity', '0039_remove_viscositymjl_lot1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viscositymjl',
            name='Konstant1',
            field=models.DecimalField(decimal_places=10, default='0', max_digits=20, verbose_name='Константа вискозиметра № 1'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='Konstant2',
            field=models.DecimalField(decimal_places=10, default='0', max_digits=20, verbose_name='Константа вискозиметра № 2'),
        ),
    ]
