# Generated by Django 4.0.4 on 2022-05-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinematicviscosity', '0040_alter_viscositymjl_konstant1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viscositymjl',
            name='Konstant2',
            field=models.DecimalField(decimal_places=10, default='0', max_digits=20, null=True, verbose_name='Константа вискозиметра № 2'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='ViscosimeterNumber2',
            field=models.CharField(default='0', max_length=10, null=True, verbose_name='Заводской номер вискозиметра № 2'),
        ),
    ]
