# Generated by Django 4.0.4 on 2022-05-25 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kinematicviscosity', '0041_alter_viscositymjl_konstant2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viscositymjl',
            name='Konstant2',
            field=models.DecimalField(blank=True, decimal_places=10, default='0', max_digits=20, verbose_name='Константа вискозиметра № 2'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='ViscosimeterNumber2',
            field=models.CharField(blank=True, default='0', max_length=10, verbose_name='Заводской номер вискозиметра № 2'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='accMeasurement',
            field=models.DecimalField(blank=True, decimal_places=1, default=1, max_digits=5, verbose_name='Оценка приемлемости измерений'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='certifiedValue',
            field=models.DecimalField(blank=True, decimal_places=10, default=1, max_digits=20, verbose_name='Аттестованное значение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='constit',
            field=models.CharField(blank=True, choices=[('да', 'Проба содержит октол/нефть'), ('нет', 'В пробе нет октола/нефти'), ('другое', 'другое')], default='Проба содержит октол/нефть', max_length=300),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='deltaOldCertifiedValue',
            field=models.DecimalField(blank=True, decimal_places=4, default=1, max_digits=10, verbose_name='Оценка разницы с предыдущим значением'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='deltaOldCertifiedValue_text',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='kriteriy',
            field=models.DecimalField(blank=True, decimal_places=1, default=1, max_digits=2, verbose_name='Критерий приемлемости измерений'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='plustimeminK1T1',
            field=models.DecimalField(blank=True, decimal_places=0, default=1, max_digits=3, verbose_name='Время истечения K1T1, + мин'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='plustimeminK1T2',
            field=models.DecimalField(blank=True, decimal_places=0, default=1, max_digits=3, verbose_name='Время истечения K1T2, + мин'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='plustimeminK2T1',
            field=models.DecimalField(blank=True, decimal_places=0, default=1, max_digits=3, verbose_name='Время истечения K2T1, + мин'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='plustimeminK2T2',
            field=models.DecimalField(blank=True, decimal_places=0, default=1, max_digits=3, verbose_name='Время истечения K2T2, + мин'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='plustimesekK1T1',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=5, verbose_name='Время истечения K1T1, + cек'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='plustimesekK1T2',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=5, verbose_name='Время истечения K1T2, + cек'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='plustimesekK2T1',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=5, verbose_name='Время истечения K2T1, + cек'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='plustimesekK2T2',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=5, verbose_name='Время истечения K2T2, + cек'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='relerror',
            field=models.DecimalField(blank=0.3, decimal_places=1, default=1, max_digits=3, verbose_name='Относительная  погрешность'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='resultMeas',
            field=models.CharField(blank=True, default='неудовлетворительно', max_length=100, verbose_name='Результат измерений уд/неуд'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='resultWarning',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='termostatition_words',
            field=models.CharField(blank=True, default=1, max_length=1, verbose_name='Термостатировано не менее 20 минут - словами'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='timeK1T1_sec',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, verbose_name='Время истечения K1T1, в секундах'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='timeK1T2_sec',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, verbose_name='Время истечения K1T2, в секундах'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='timeK1_avg',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, verbose_name='Время истечения среднее 1, в секундах'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='timeK2T1_sec',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, verbose_name='Время истечения K2T1, в секундах'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='timeK2T2_sec',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, verbose_name='Время истечения K2T2, в секундах'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='timeK2_avg',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, verbose_name='Время истечения среднее 2, в секундах'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='viscosity1',
            field=models.DecimalField(blank=True, decimal_places=7, default=0.0, max_digits=20, verbose_name='Вязкость кинематическая 1'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='viscosity2',
            field=models.DecimalField(blank=True, decimal_places=7, default=0.0, max_digits=20, verbose_name='Вязкость кинематическая 2'),
        ),
        migrations.AlterField(
            model_name='viscositymjl',
            name='viscosityAVG',
            field=models.DecimalField(blank=True, decimal_places=7, default=0.0, max_digits=20, verbose_name='Вязкость кинематическая среднее'),
        ),
        migrations.CreateModel(
            name='CommentsKinematicviscosity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, db_index=True, verbose_name='Дата')),
                ('name', models.TextField(default='', max_length=1000, verbose_name='Наименование')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Наименование')),
                ('forNote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinematicviscosity.viscositymjl', verbose_name='Наименование')),
            ],
        ),
    ]
