# Generated by Django 4.0.4 on 2022-05-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinematicviscosity', '0043_alter_viscositymjl_konstant2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentskinematicviscosity',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterField(
            model_name='commentskinematicviscosity',
            name='name',
            field=models.TextField(default='', max_length=1000, verbose_name='Содержание'),
        ),
    ]
