# Generated by Django 4.0.4 on 2022-05-25 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kinematicviscosity', '0044_alter_commentskinematicviscosity_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentskinematicviscosity',
            name='forNote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinematicviscosity.viscositymjl', verbose_name='К странице аттестации'),
        ),
    ]
