# Generated by Django 4.0.4 on 2022-05-26 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kinematicviscosity', '0045_alter_commentskinematicviscosity_fornote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentskinematicviscosity',
            name='forNote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='kinematicviscosity.viscositymjl', verbose_name='К странице аттестации'),
        ),
    ]
