# Generated by Django 4.0.4 on 2022-05-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinematicviscosity', '0046_alter_commentskinematicviscosity_fornote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentskinematicviscosity',
            name='author',
        ),
        migrations.RemoveField(
            model_name='commentskinematicviscosity',
            name='forNote',
        ),
        migrations.AlterField(
            model_name='commentskinematicviscosity',
            name='name',
            field=models.CharField(default='', max_length=1000, verbose_name='Содержание'),
        ),
    ]
