# Generated by Django 4.0.4 on 2022-05-26 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kinematicviscosity', '0047_remove_commentskinematicviscosity_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentskinematicviscosity',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Наименование'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commentskinematicviscosity',
            name='forNote',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='kinematicviscosity.viscositymjl', verbose_name='К странице аттестации'),
            preserve_default=False,
        ),
    ]
