# Generated by Django 4.0.4 on 2022-05-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinematicviscosity', '0048_commentskinematicviscosity_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentskinematicviscosity',
            name='name',
            field=models.TextField(default='', max_length=1000, verbose_name='Содержание'),
        ),
    ]
